[package]
name = "core"
version = "0.1.0"
authors = ["FenQiDian <email@fenqi.moe>"]
edition = "2018"

[dependencies]
alga = "0.9"
approx = "0.3"
derivative = "2"
derive = { path = "../derive" }
euclid = "0.20"
failure = "0.1"
fixed = "1"
lazy_static = "1"
libc = "0.2"
math = { path = "../math" }
nalgebra = { version = "0.21", features = [ "serde-serialize" ] }
ncollide3d = { version = "0.23", features = [ "improved_fixed_point_support" ] }
serde = { version = "1" , features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
simba = { version = "0.1", features = [ "partial_fixed_point_support" ] }
